### PR TITLE
Use `actual` to decide if we should use JSX helpers.

### PR DESCRIPTION
**Pull request by tvararu**
Hey there!

This simple change uses the `actual` value to decide whether it should switch over to our JSX asserters. It allows me to do stuff like this:

``` javascript
Comp = () => <span>Left</span>

output = render(<Comp />)
expect(output).to.include('Left')
```

Which is a lot less ceremony for just checking if a string appears deeply inside a component hierarchy, and shouldn't affect anything.

I couldn't run the tests; after running an `npm install` they crashed with this error message:

```
$ npm test

> jsx-chai@1.1.1 test /Users/tvararu/github/jsx-chai
> istanbul cover _mocha

No coverage information was collected, exit without writing coverage information
module.js:329
    throw err;
    ^

Error: Cannot find module 'react/lib/ReactTestUtils'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
```

If there's anything else that needs to be updated, let me know. :ok_hand:

### CODE REVIEW

**Comment by bkonkle** [comment]
Nice! Thank you for the contribution! I'll plan to check it out today and likely merge it.

**Comment by bkonkle** [comment]
As far as running the tests goes, you'll need to install the peerDependencies as well:

``` js
npm install react redux
```

I added that to the README.

**Comment by bkonkle** [comment]
I'm having trouble writing a regression test that fails on `develop`. This test passes without your changes:

``` js
    it('uses the underlying JSX object to determine if jsx-chai should be used', () => {
      const Component = () => <span>Left</span>

      expect(
        () => expect(<Component/>).to.include('Left')
      ).to.not.throw()
    })
```

~~Where does `render()` come from in your example?~~ I'm going to assume it comes from ReactDOM.

**Comment by bkonkle** [comment]
There we go - this test does it:

``` js
    it('uses the underlying JSX object to determine if jsx-chai should be used', () => {
      class Component {
        render() {
          return <span>Left</span>
        }
      }

      const result = Component.prototype.render()

      expect(
        () => expect(result).to.include('Left')
      ).to.not.throw()
    })
```

**Comment by bkonkle** [comment]
Thanks again for the contribution!

**Comment by tvararu** [comment]
:tada: Thanks for the quick turnaround!

**Pull request merged**
